# Configure the database used when in the development environment
development:
  adapter: postgresql
  encoding: unicode
  database: evening_ar_brussels_development
  pool: 5
  username:
  password:

# Configure the database used when in the test environment
test:
  adapter: postgresql
  encoding: unicode
  database: evening_ar_brussels_test
  pool: 5
  username:
  password:

# Configure the database used when in the production environment
production:
  adapter: postgresql
  encoding: unicode
  database: evening_ar_brussels_production
  pool: 5
  username:
  password:
