recipe1 = Recipe.create(name: "Mangu", description: "Delicious Dominican shit")
recipe2 = Recipe.create(name: "Morir Sonando", description: "Bestest beverage ever.")
recipe3 = Recipe.create(name: "Pastelon", description: "Sweet plantains, ground beef, cheese. Yum")
recipe4 = Recipe.create(name: "Queso Frito", description: "Fried cheese")
recipe5 = Recipe.create(name: "Salchichon", description: "Fried salami")

Comment.create(title: "Delicious", description: "Yummy shit", recipe: recipe1)
Comment.create(title: "Even more delicious", description: "Yummy yummy shit", recipe: recipe2)
Comment.create(title: "Even more more delicious", description: "Yummy yummy yummy shit", recipe: recipe3)
Comment.create(title: "Even more more more delicious", description: "Yummy yummy yummy shit", recipe: recipe4)
Comment.create(title: "Even more more more delicious", description: "Yummy yummy yummy yummy shit", recipe: recipe5)
